[package]
name = "pestvsnom"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
libc = "^0.2"

[build-dependencies]
gcc = "^0.3"

[dev-dependencies]
pest = "^2"
pest_grammars = "^2"
nom = "^4"
